language: haskell

sudo: false
cache:
  directories:
  - $HOME/.stack/

before_install:
  # stack
  - mkdir -p ~/.local/bin
  - export PATH=~/.local/bin:$PATH
  - travis_retry curl -L https://github.com/commercialhaskell/stack/releases/download/v0.1.4.0/stack-0.1.4.0-x86_64-linux.tar.gz | tar xz -C ~/.local/bin
  - chmod a+x ~/.local/bin/stack

install:
  - stack --no-terminal setup
  - stack --no-terminal build --only-snapshot

script:
  - stack --no-terminal test

notifications:
  slack:
    on_success: change
    on_failure: always
    secure: V61m9h0cnvpQ3Gx97uwBpUvsB8uV8l4J3152X14t5T2OGkihJ0udTykB9nozH9RQiGqXVl9Q5aSZTaqPoVpRYTBbclVXdYs5VN68TzYuAGulXzy6JW26ujiSvf6sihJVa1s0FB3q3l4r5dWD5geygFnujVAdFZ+zRLcAiGWpE2ZthL48gl2ATUs4oOVjzBMHZcpuU8nxzVU0dQl/5WBxIJQJEDPKzN/pYARBEzuVRNwn9KzS0IDClrk5Cjuxpj3A5FrIpj24uS2z31ybA1l/MWLVX4lAXKSQ8qIDrYhHiF86bPnqQ16WHN/PkCVEqw/NQdXAzCABhS8O/uDEEZCHoIK8dR6CmKAhvDvpqd1ydB9ukfR2ntaBEKTPB3QxOky6LFmwQiEIIPHMJ+xlRNUUrTkrqnZSUyJSGDALS+rksy/DBt03WC7qN5+FTXVBCJEla4zqQCFe0MAN8bWQzdLTrbtRdGuwgJknzohwXdAODsRRIMHzsMGlWTcj3007AV2ddsYuSnnS+4gRnZ19MS2CQWAgCDqGoR0lFlr5EEEUvE97cnoVHj4WUlhVm6fVwN56jdNR85B21TuRKfQ9k3Zpd/TPbMqt5HscJWiG5yKuW/A3nNKzRVU63meS91tgru7fET9ctB4t5twA0TC8renKqVN6tjlDcjSXzvuTFIJYOC4=
